### ISSUE TITLE
ERROR command to get status of k8s-app=cilium has failed. error code: 1 b'error: name cannot be provided when a selector is specified'

### ISSUE THREAD

**Issue by zhujik** [cilium/cilium-sysdump#110]
> curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
DEBUG Fetching nodes to determine cluster size...
INFO collecting cilium gops stats ...
INFO collecting kubernetes version info ...
INFO collecting Kubernetes events JSON ...
INFO collecting Kubernetes namespaces yaml ...
INFO collecting nodes overview ...
INFO collecting pods overview ...
INFO collecting pods summary ...
INFO collecting services overview ...
ERROR command to get status of k8s-app=cilium has failed. error code: 1 b'error: name cannot be provided when a selector is specified\n'
ERROR command to get status of k8s-app=cilium has failed. error code: 1 b'error: name cannot be provided when a selector is specified\n'
ERROR command to get status of k8s-app=cilium has failed. error code: 1 b'error: name cannot be provided when a selector is specified\n'
INFO collecting hubble gops stats ...
ERROR command to get status of k8s-app=hubble has failed. error code: 1 b'error: name cannot be provided when a selector is specified\n'
ERROR command to get status of k8s-app=hubble has failed. error code: 1 b'error: name cannot be provided when a selector is specified\n'
ERROR command to get status of k8s-app=hubble has failed. error code: 1 b'error: name cannot be provided when a selector is specified\n'
INFO collecting hubble relay gops stats ...
ERROR command to get status of k8s-app=hubble-relay has failed. error code: 1 b'error: name cannot be provided when a selector is specified\n'
INFO collected kubernetes namespaces: k8s-namespaces-20210308-105247.yaml
ERROR command to get status of k8s-app=hubble-relay has failed. error code: 1 b'error: name cannot be provided when a selector is specified\n'
INFO collected nodes overview: nodes-20210308-105247.json
INFO collected kubernetes version info: k8s-version-info-20210308-105247.txt
INFO collected kubernetes events: k8s-events-20210308-105247.json
INFO collected svc overview: services-20210308-105247.yaml
ERROR command to get status of k8s-app=hubble-relay has failed. error code: 1 b'error: name cannot be provided when a selector is specified\n'
INFO collecting cilium-bugtool output ...
INFO collecting kubernetes network policy ...
INFO collecting cilium network policy ...
INFO collecting cilium clusterwide network policy ...
INFO collecting cilium etcd secret ...
INFO collecting cilium identities ...
INFO collecting cilium endpoints ...
INFO collected pods overview: pods-20210308-105247.json
INFO collecting cilium nodes ...
INFO collected pods summary: pods-20210308-105247.txt
INFO collecting cilium daemonset yaml ...
ERROR command to get status of k8s-app=cilium has failed. error code: 1 b'error: name cannot be provided when a selector is specified\n'
INFO collecting cilium logs ...
ERROR command to get status of k8s-app=cilium has failed. error code: 1 b'error: name cannot be provided when a selector is specified\n'
INFO collecting cilium operator logs ...
ERROR command to get status of io.cilium/app=operator has failed. error code: 1 b'error: name cannot be provided when a selector is specified\n'
INFO collecting hubble logs ...
ERROR command to get status of k8s-app=hubble has failed. error code: 1 b'error: name cannot be provided when a selector is specified\n'
INFO collecting hubble relay logs ...
ERROR command to get status of k8s-app=hubble-relay has failed. error code: 1 b'error: name cannot be provided when a selector is specified\n'
INFO Command 'kubectl get secret cilium-etcd-secrets -n kube-system -o json' returned non-zero exit status 1.. Unable to get and redact cilium secret (this is expected in CRD mode).
INFO collecting hubble daemonset yaml ...
INFO collected cilium clusterwide network policy: ccnp-20210308-105252.yaml
INFO collecting cilium configmap yaml ...
INFO collected cilium endpoints: cep-20210308-105252.yaml
INFO collected kubernetes network policy: netpol-20210308-105252.yaml
INFO collected cilium network policy: cnp-20210308-105252.yaml
INFO collected cilium identities: ciliumidentities-20210308-105252.yaml
INFO collected cilium daemonset yaml file: cilium-ds-20210308-105253.yaml
INFO collected cilium nodes: ciliumnodes-20210308-105253.yaml
INFO collected cilium configmap yaml file: cilium-configmap-20210308-105256.yaml
INFO deleting directory: ./cilium-sysdump-20210308-105247
INFO the sysdump has been saved in the file C:\tmp\cilium-sysdump-20210308-105247.zip.

Sysdump seems incomplete.

**Comment by pchaigno** [comment]
What `kubectl` version are you using?

The error seems to imply that we passed both a selector and a pod name to `kubectl get pods`, as in e.g. `k get pods --selector="k8s-app=cilium" cilium-n678n`. The error seems to come from:
https://github.com/cilium/cilium-sysdump/blob/ef8028470906ba18a6cf512df704b18a4f29eb61/cilium-sysdump/utils.py#L194
except that command doesn't pass a pod name. It only use a selector, in this case, `k8s-app=cilium`.

Any chance you could run something like `execsnoop-bpfcc` (from [the bcc tools](https://github.com/iovisor/bcc)) while taking the sysdump so that we see exactly what `kubectl` command is failing?

**Comment by zhujik** [comment]
@pchaigno 
Kubectl and Kubernetes Versions:
EKS 1.18
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
I can run the tool you mentioned next week when I'm back at work.

**Comment by michi-covalent** [comment]
we are migrating to a new implementation of sysdump: `cilium sysdump`: https://github.com/cilium/cilium-cli. could you try the new sysdump and open a new issue in the cilium-cli repo if you continue to see this issue. thanks!
