### ISSUE TITLE
Init container logs from Cilium agent pod are not collected

### ISSUE THREAD

**Issue by aditighag** [cilium/cilium-sysdump#120]
We don't seem to collect logs from init containers (although, from a cursory glance I do see that we iterate over all the containers in a pod while collecting logs). For example, this run - https://github.com/cilium/cilium/pull/16815/checks?check_run_id=3005100569 failed because an init container in the cilium agent pod was failing, and the collected sysdump had empty cilium pod logs.  

[cilium-sysdump-out.zip (8).zip](https://github.com/cilium/cilium-sysdump/files/6774283/cilium-sysdump-out.zip.8.zip)

**Comment by joestringer** [comment]
PR to fix it in new cilium-cli sysdump: https://github.com/cilium/cilium-cli/pull/414

**Comment by aditighag** [comment]
@joestringer We use this utility to collect sysdump in the workflow jobs - https://github.com/cilium/cilium/blob/master/.github/workflows/tests-smoke.yaml#L172.
