### ISSUE TITLE
Consider using asyncio to speed up execution time

### ISSUE THREAD

**Issue by evanfoster** [cilium/cilium-sysdump#88]
On larger clusters, a full Cilium sysdump can take upwards of 20 minutes. I may need to run many full sysdumps on large clusters, so I converted the code to use `asyncio`. With my changes, all collection steps run concurrently. On a cluster with ~90 nodes:
```
Full sysdump
Old: 19m37s
New: 7m41s

Quick sysdump
Old: 4m34s
New: 53s
```

Additionally, I've tested using a very small cluster (<10 nodes):
```
Full sysdump
Old: 2m39s
New: 1m11s

Quick sysdump
Old: 45s
New: 13s
```

Would there be interest in these changes? If so, I'd be happy to submit a PR. An important note is that this would limit `cilium-sysdump` to Python versions >= 3.5, but preferably >= 3.6. The code changes aren't too dramatic otherwise (142 insertions(+), 159 deletions(-), although this will grow so I can add concurrency controls).

**Comment by evanfoster** [comment]
I'll be attaching a patch shortly.

**Comment by evanfoster** [comment]
Here's a patch of what I've done: https://gist.github.com/evanfoster/64c5e3d194eb7546953729bd95fe915c

**Comment by joestringer** [comment]
This will be resolved with the upcoming migration of cilium-sysdump to Go as part of the new Cilium CLI: https://github.com/cilium/cilium-cli/tree/v0.8.4/sysdump
