### ISSUE TITLE
sysdump utility should include a recent cache of Hubble data

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium-sysdump#93]
We are discussing this topic in the following thread on Cilium side:

https://github.com/cilium/cilium/issues/11841

This issue helps to track for any necessary changes on the cilium-sysdump side.

**Comment by michi-covalent** [comment]
this is implemented in the new sysdump: https://github.com/cilium/cilium-cli/commit/4f2d3eb5cd0a9f4e0af92599e9a88301302e1727. closing this issue.
