### ISSUE TITLE
UnboundLocalError: local variable 'output' referenced before assignment

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium-sysdump#99]
I got the following error in our Cilium Smoke test when trying to take a sysdump:
```
Run curl -sLO https://github.com/cilium/cilium-sysdump/releases/latest/download/cilium-sysdump.zip
DEBUG Fetching nodes to determine cluster size...
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "cilium-sysdump.zip/__main__.py", line 148, in <module>
  File "cilium-sysdump.zip/utils.py", line 236, in get_nodes
UnboundLocalError: local variable 'output' referenced before assignment
Error: Process completed with exit code 1.
```
AFAICS, this is caused by the following code:
https://github.com/cilium/cilium-sysdump/blob/260b4828915e65d5307d247964efb34bbb4f215c/cilium-sysdump/utils.py#L281-L287
On line 287, we reference `output` even though that variable doesn't exist if the previous statement resulted in an exception. We seem to have this pattern in several places.

/cc @christarazi

**Comment by christarazi** [comment]
Fixed by https://github.com/cilium/cilium-sysdump/pull/102
